// models/city.dart
//
// A populated place from the offline city database (assets/data/cities.json,
// generated by tool/build_cities.py from the GeoNames cities15000 dump).
// Names are Arabic + English only, with an IANA timezone for prayer times.

/// Arabic name of a country, falling back to English when unavailable.
class CountryInfo {
  final String code;
  final String? nameAr;
  final String nameEn;

  const CountryInfo({
    required this.code,
    required this.nameAr,
    required this.nameEn,
  });

  /// Name to show in the Arabic UI.
  String get displayName => nameAr ?? nameEn;

  factory CountryInfo.fromJson(String code, Map<String, dynamic> json) {
    return CountryInfo(
      code: code,
      nameAr: json['ar'] as String?,
      nameEn: (json['en'] as String?) ?? code,
    );
  }
}

class City {
  /// English (ASCII) name, always present. Also the search fallback when
  /// no Arabic name exists.
  final String nameEn;

  /// Clean Modern Standard Arabic name, or null when GeoNames has none
  /// (small towns). The UI then shows [nameEn].
  final String? nameAr;

  /// ISO country code, resolved via [CityDirectory.countryLabel].
  final String countryCode;
  final double latitude;
  final double longitude;

  /// IANA timezone supplied by GeoNames, e.g. `Africa/Cairo`.
  final String? timeZone;

  const City({
    required this.nameEn,
    required this.nameAr,
    required this.countryCode,
    required this.latitude,
    required this.longitude,
    this.timeZone,
  });

  /// Primary display name in the Arabic UI.
  String get displayName => nameAr ?? nameEn;

  factory City.fromJson(Map<String, dynamic> json) {
    return City(
      nameEn: json['en'] as String,
      nameAr: json['ar'] as String?,
      countryCode: json['country'] as String,
      latitude: (json['lat'] as num).toDouble(),
      longitude: (json['lng'] as num).toDouble(),
      timeZone: json['tz'] as String?,
    );
  }
}
