name: aldurar_alnaqia
description: "تطبيق الدرر النقية يحتوى على أوراد الطريقة اليسرية الصديقية الشاذلية"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  adhan_dart: ^2.0.0
  audio_service: ^0.18.19
  audio_session: ^0.2.4
  background_downloader: ^9.1.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.2
  geolocator: ^14.0.0
  go_router: ^18.0.1
  hijri: ^3.0.0
  intl: any
  just_audio: ^0.10.0
  lottie: ^3.3.1
  lucide_icons_flutter: ^3.1.20
  material_ui: ^1.3.0
  path_provider: ^2.1.3
  pdfx: ^2.7.0
  permission_handler: ^13.0.2
  shared_preferences: ^2.2.3
  timezone: ^0.11.0
  url_launcher: ^6.3.0
dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  plugin_platform_interface: any
  url_launcher_platform_interface: any
  very_good_analysis: ^11.0.0
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "app_logo_cropped.png"
  image_path_android: "app_logo_cropped.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "app_logo_cropped.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "app_logo_cropped.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "app_logo_cropped.png"

flutter:
  uses-material-design: true

  assets:
    - assets/pdfs/
    - assets/imgs/
    - assets/lottie/
    - assets/imgs/sunnah_midnight.png
    - assets/imgs/sunnah_last_third.png
    - assets/imgs/sunnah_duha.png
    - assets/icons/
    - assets/data/

  fonts:
    - family: NotoNaskh
      fonts:
        - asset: fonts/NotoNaskArabic.ttf
    - family: AmiriQuran
      fonts:
        - asset: fonts/DigitalKhatt.otf
