#!/usr/bin/env python3
"""Build the offline city database for the prayer-timings city picker.

Reads the GeoNames ``cities15000`` dump (all populated places with
population > 15000, ~34k entries) and produces a compact JSON asset with
**Arabic + English names only**:

    assets/data/cities.json

Schema::

    {
      "version": 1,
      "attribution": "...",
      "countries": {"EG": {"ar": "مصر", "en": "Egypt"}, ...},
      "cities": [
        {"en": "Cairo", "ar": "القاهرة", "country": "EG",
         "lat": 30.063, "lng": 31.250},
        ...
      ]
    }

* ``cities`` is sorted by population (descending) so the app can use the
  position as a popularity signal for search ranking.
* ``ar`` is omitted when no clean Arabic name exists; the app then shows
  and searches the English name.
* Coordinates are rounded to 3 decimals (~110 m, far more precise than
  prayer-time math needs) to keep the asset small.

Arabic-name extraction: GeoNames ``alternatenames`` mixes Arabic with
Urdu / Persian / Uyghur spellings written in Arabic script.  Candidates
are restricted to core Arabic letters (U+0621-U+064A, i.e. no Persian
gaf/kaf/yeh etc.), diacritics are stripped, then scored: bonus for the
``ال`` prefix and proper orthography (``أإآؤئة``), penalty for
administrative qualifiers (``إمارة``/``ولاية``/...) and long
descriptions.  Egyptian towns missing from GeoNames Arabic alternates
get curated overrides in ``AR_OVERRIDES``.

Usage::

    python3 tool/build_cities.py [--work-dir /tmp/citydata] [--force]

The script downloads (once, cached in ``work-dir``):
  * https://download.geonames.org/export/dump/cities15000.zip  (CC BY 4.0)
  * https://raw.githubusercontent.com/umpirsky/country-list/master/data/ar/country.json  (MIT)
  * https://raw.githubusercontent.com/umpirsky/country-list/master/data/en/country.json  (MIT)
"""

from __future__ import annotations

import argparse
import json
import re
import urllib.request
import zipfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_PATH = REPO_ROOT / "assets" / "data" / "cities.json"

CITIES_URL = "https://download.geonames.org/export/dump/cities15000.zip"
COUNTRIES_AR_URL = (
    "https://raw.githubusercontent.com/umpirsky/country-list/master"
    "/data/ar/country.json"
)
COUNTRIES_EN_URL = (
    "https://raw.githubusercontent.com/umpirsky/country-list/master"
    "/data/en/country.json"
)

ATTRIBUTION = (
    "City coordinates (c) GeoNames (CC BY 4.0, geonames.org), "
    "cities15000 dump. Arabic/English country names (c) "
    "umpirsky/country-list (MIT). Generated by tool/build_cities.py."
)

# --- Arabic extraction -----------------------------------------------------

# Core Arabic letters only: U+0621-U+064A + space.  Excludes Persian/Urdu
# extensions (گ چ پ ژ ے ھ ە ...) so Urdu/Persian/Uyghur variants drop out.
CORE_ARABIC = re.compile(r"^[\u0621-\u064A ]+$")
ARABIC_SCRIPT = re.compile(r"[\u0600-\u06FF]")
# Diacritics and tatweel: removed. Zero-width joiners: turned into spaces
# (they join compound names, e.g. 'باب\u200cالزوار' -> 'باب الزوار').
REMOVE_CHARS = re.compile(r"[\u064B-\u0652\u0670\u0640]")
SPACE_CHARS = re.compile(r"[\u200C\u200D]")
MULTISPACE = re.compile(r"\s+")

# Administrative/descriptive qualifiers: picking the bare city name reads
# better in a picker ("الشارقة" not "إمارة الشارقة").
QUALIFIERS = {
    "إمارة",
    "امارة",
    "ولاية",
    "محافظة",
    "مقاطعة",
    "استان",
    "جزيرة",
    "بلدية",
    "إقليم",
    "اقليم",
    "مدينة",
}
# Bonus for proper MSA orthography: hamza forms, ta-marbuta and ya
# (dialectal variants tend to write ا/ه/ى instead).
PROPER_BONUS_CHARS = "أإآؤئةي"


def clean_candidate(raw: str) -> str:
    """Strip diacritics/tatweel and collapse whitespace."""
    no_marks = REMOVE_CHARS.sub("", raw)
    spaced = SPACE_CHARS.sub(" ", no_marks)
    return MULTISPACE.sub(" ", spaced).strip()


def score_candidate(name: str) -> int:
    words = name.split(" ")
    score = len(name)
    if name.startswith("ال"):
        score += 3
    score += sum(name.count(ch) for ch in PROPER_BONUS_CHARS)
    score -= 10 * sum(1 for w in words if w in QUALIFIERS)
    if len(words) > 2:
        score -= 3 * (len(words) - 2)
    return score


def best_arabic_name(alternates_raw: str) -> str | None:
    """Pick one clean Modern Standard Arabic name, or None."""
    seen: set[str] = set()
    candidates: list[str] = []
    for raw in alternates_raw.split(","):
        if not ARABIC_SCRIPT.search(raw):
            continue
        name = clean_candidate(raw)
        if len(name) < 2 or name in seen:
            continue
        seen.add(name)
        if CORE_ARABIC.match(name):
            candidates.append(name)
    if not candidates:
        return None
    # Prefer concise names: drop long descriptions when a short name exists
    # (e.g. keep 'أبوظبي', not 'جزيرة أبوظبي وجزر داخلية اخرى').
    short = [n for n in candidates if len(n.split(" ")) <= 3]
    if short:
        candidates = short
    candidates.sort(key=lambda n: (-score_candidate(n), len(n.split(" ")), len(n)))
    return candidates[0]


# Curated Arabic names for Egyptian towns that have NO Arabic alternate in
# GeoNames.  Key: (asciiname, country code).  Deliberately conservative:
# towns not listed here fall back to their English name.
AR_OVERRIDES: dict[tuple[str, str], str] = {
    ("6th of October City", "EG"): "مدينة السادس من أكتوبر",
    ("Abu Suweir-el-Mahatta", "EG"): "أبو صوير",
    ("Abu al Matamir", "EG"): "أبو المطامير",
    ("Abu an Numrus", "EG"): "أبو النمرس",
    ("Al 'Ayn as Sukhnah", "EG"): "العين السخنة",
    ("Al 'Ayyat", "EG"): "العياط",
    ("Al Badrashayn", "EG"): "البدرشين",
    ("Al Hawamidiyah", "EG"): "الحوامدية",
    ("Al Khankah", "EG"): "الخانكة",
    ("Al Wasitah", "EG"): "الواسطة",
    ("Al-Kharijah", "EG"): "الخارجة",
    ("Al Khusus", "EG"): "الخصوص",
    ("Al-Minya al-Jadidah", "EG"): "المنيا الجديدة",
    ("Ar Radisiyah Qibli", "EG"): "الرديسية قبلي",
    ("Ar-Rawdah", "EG"): "الروضة",
    ("Atfih", "EG"): "أطفيح",
    ("Badr", "EG"): "بدر",
    ("Bani Suwayf al Jadidah", "EG"): "بني سويف الجديدة",
    ("Basyun", "EG"): "بسيون",
    ("Daraw", "EG"): "دراو",
    ("Fayid", "EG"): "فايد",
    ("Hala'ib", "EG"): "حلايب",
    ("Hawsh 'Isa", "EG"): "حوش عيسى",
    ("Ihnasya al Madinah", "EG"): "إهناسيا المدينة",
    ("Kafr Shukr", "EG"): "كفر شكر",
    ("Kom Ombo", "EG"): "كوم أمبو",
    ("Madinat an Nasr", "EG"): "مدينة نصر",
    ("Madinat as Sadat", "EG"): "مدينة السادات",
    ("Mashtul as Suq", "EG"): "مشتول السوق",
    ("Mut", "EG"): "موط",
    ("New Bani Sewif City", "EG"): "مدينة بني سويف الجديدة",
    ("Ras Gharib", "EG"): "رأس غارب",
    ("Sinnuris", "EG"): "سنورس",
    ("Sumusta as Sultani", "EG"): "سمسطا",
    ("Tamiyah", "EG"): "طامية",
    ("Yusuf as-Siddiq", "EG"): "يوسف الصديق",
    ("Zaafarana", "EG"): "الزعفرانة",
}


# --- Download helpers ------------------------------------------------------


def download(url: str, dest: Path, force: bool = False) -> Path:
    if dest.exists() and not force:
        print(f"  reuse {dest.name}")
        return dest
    print(f"  downloading {url} ...")
    dest.parent.mkdir(parents=True, exist_ok=True)
    with urllib.request.urlopen(url, timeout=120) as resp, open(dest, "wb") as fh:
        fh.write(resp.read())
    return dest


# --- Main ------------------------------------------------------------------


def build(work_dir: Path, force: bool = False) -> dict:
    cities_zip = download(CITIES_URL, work_dir / "cities15000.zip", force)
    ar_path = download(COUNTRIES_AR_URL, work_dir / "countries_ar.json", force)
    en_path = download(COUNTRIES_EN_URL, work_dir / "countries_en.json", force)

    with open(ar_path, encoding="utf-8") as fh:
        countries_ar: dict[str, str] = json.load(fh)
    with open(en_path, encoding="utf-8") as fh:
        countries_en: dict[str, str] = json.load(fh)

    with zipfile.ZipFile(cities_zip) as zf:
        names = [n for n in zf.namelist() if n.endswith(".txt")]
        raw = zf.read(names[0]).decode("utf-8")

    entries: list[tuple[int, dict]] = []
    missing_ar = 0
    for line in raw.splitlines():
        if not line.strip():
            continue
        f = line.split("\t")
        # GeoNames dump columns: 0 id, 1 name, 2 asciiname, 3 alternates,
        # 4 lat, 5 lng, 8 country code, 14 population.
        asciiname = f[2] or f[1]
        country = f[8]
        try:
            population = int(f[14] or 0)
        except ValueError:
            population = 0
        ar = best_arabic_name(f[3])
        if ar is None:
            ar = AR_OVERRIDES.get((asciiname, country))
        if ar is None:
            missing_ar += 1
        city: dict = {
            "en": asciiname,
            "country": country,
            "lat": round(float(f[4]), 3),
            "lng": round(float(f[5]), 3),
        }
        if ar is not None:
            city["ar"] = ar
        entries.append((population, city))

    entries.sort(key=lambda e: -e[0])
    cities = [c for _, c in entries]

    used_countries = sorted({c["country"] for c in cities})
    countries = {
        code: {
            "ar": countries_ar.get(code),
            "en": countries_en.get(code, code),
        }
        for code in used_countries
    }
    # Drop null Arabic country names (app falls back to English).
    for info in countries.values():
        if info["ar"] is None:
            del info["ar"]

    # --- Regional overrides ------------------------------------------------
    # Jerusalem (GeoNames lists it under IL) belongs to Palestine in this
    # app; all other IL entries are dropped.
    for c in cities:
        if c.get("country") == "IL" and c.get("en") == "Jerusalem":
            c["country"] = "PS"
            c["ar"] = "القدس الشريف"
    cities = [
        c for c in cities
        if c.get("country") != "IL"
    ]
    countries.pop("IL", None)
    if "PS" in countries:
        countries["PS"] = {"ar": "فلسطين", "en": "Palestine"}

    with_ar = sum(1 for c in cities if "ar" in c)
    print(f"  cities: {len(cities)} ({with_ar} with Arabic name)")
    print(f"  cities without Arabic (English fallback): {missing_ar}")
    print(f"  countries: {len(countries)}")
    return {"version": 1, "attribution": ATTRIBUTION,
            "countries": countries, "cities": cities}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--work-dir", type=Path,
                        default=Path("/tmp/opencode/citydata"))
    parser.add_argument("--force", action="store_true",
                        help="re-download cached source files")
    args = parser.parse_args()

    print("Building offline city database ...")
    data = build(args.work_dir, args.force)
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT_PATH, "w", encoding="utf-8") as fh:
        json.dump(data, fh, ensure_ascii=False, separators=(",", ":"))
    size_mb = OUT_PATH.stat().st_size / 1e6
    print(f"  wrote {OUT_PATH} ({size_mb:.2f} MB)")


if __name__ == "__main__":
    main()
